name: ackable
description: Ack messages from different sources.
version: 0.0.1
repository: https://github.com/jodinathan/ackable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.0.2
  supercharged_dart: ^2.1.1
  dispose: ^0.0.9+1
  meta: ^1.7.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.3
  quiver: ^3.2.1
  collection: ^1.18.0
  shelf: any
  typings: any

dev_dependencies:
  effective_dart: ^1.3.2
  lints: ^2.0.0

