name: ackable
description: Ack messages from different sources.
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  supercharged_dart: ^2.1.1
  lints: ^1.0.1
  dispose: ^0.0.6
  meta: ^1.7.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  quiver: ^3.0.1+1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  effective_dart: ^1.3.2

dependency_overrides:
  dispose:
    path: ../dispose
